### PR TITLE
Fix: Channel not found log to warning

### LINKED ISSUE #6: use warning level for "Channel not found, pausing for 15 minutes"
```json
{"ts":1697939145.558466,"level":"info","r":42,"file":"app.go","line":214,"msg":"Channel not found, pausing for 15 minutes","channel":"#does-not-exist"}
```

### PR DESCRIPTION
**Pull request by ani1311**
Closes #6

### CODE REVIEW

**Comment by ani1311** [comment]
Had a small NIT. Was thinking of moving line [98](https://github.com/fortio/slack-proxy/pull/12/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR97-R98) to [218](https://github.com/fortio/slack-proxy/pull/12/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR214). 

Just to the adding to `doNotProcessChannels` outside CheckError.  Wanted to check if thats ok?

**Comment by wiardvanrij** [comment]
> Had a small NIT. Was thinking of moving line [98](https://github.com/fortio/slack-proxy/pull/12/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR97-R98) to [218](https://github.com/fortio/slack-proxy/pull/12/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR214).
> 
> Just to the adding to `doNotProcessChannels` outside CheckError. Wanted to check if thats ok?

I'm not getting it, but perhaps just make the change and we can review it (and/or just make a new MR for it so we can merge this one in for sure)

**Review by ldemailly — APPROVED** [review]
Thanks, are there any more cases that are in between info and error?

**Comment by ani1311** [comment]
Maybe this could be warning: https://github.com/fortio/slack-proxy/blob/main/server.go#L60 
Queue is almost full.

**Review by wiardvanrij — APPROVED** [review]

**Pull request merged**
