### PR TITLE
Feature: Reading slack token from env flag

### LINKED ISSUE #21: Feature: Use Env var to get Slack API Tokens
We should get API token as env var because kubernetes secrets are passed as env vars which is safer than using command line args.

Another addition to this could be that env var should be a comma seperated list of tokens. This list will then be used by the stateful sets mentioned here:  https://github.com/fortio/slack-proxy/issues/20

### PR DESCRIPTION
**Pull request by ani1311**
closes #21

### CODE REVIEW

**Review by ldemailly — APPROVED** [review]
thx!

**Comment by ldemailly** [comment]
so that's 0.3.0 (incompatible (yet necessary) change)

**Comment by ldemailly** [comment]
@ani1311  Aniket, you should be able to make a release, right ? (and autogenerate release notes, then the github action will add the binary build and push the docker images)

**Comment by ani1311** [comment]
Ya, I can do the release. Making 0.3.0 now.

**Pull request merged**
